### ISSUE TITLE
Enabling features = ["mt"] breaks cargo wasm compilation

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/sylvia#104]
It pulls in getrandom. 
Even if I do

```toml
[dependencies]
sylvia = { version = "0.3.2" }

[dev-dependencies]
sylvia = { version = "0.3.2", features = ["mt"] }
```
