### ISSUE TITLE
difficult to follow up with the sylvia book

### ISSUE THREAD

**Issue by deauthe** [CosmWasm/sylvia#387]
I was going through the sylvia book, and I am getting weird errors. I have made sure to use the exact versions of dependencies as in the book and tried to copy code but the errors remain the same ,even for a very simple initial project. I am a complete noob and it might be unnecessary to post but seemed fair to me. 
<img width="925" alt="image" src="https://github.com/CosmWasm/sylvia/assets/62888566/a80d6145-fa78-4987-b211-9b5733b33c86">
<img width="925" alt="image" src="https://github.com/CosmWasm/sylvia/assets/62888566/5b71b3a6-c6bd-4a19-b5d5-22643bc70517">
<img width="925" alt="image" src="https://github.com/CosmWasm/sylvia/assets/62888566/2aa2b788-0d5d-4f11-94b6-e74efde77608">
<img width="925" alt="image" src="https://github.com/CosmWasm/sylvia/assets/62888566/89e971cf-85cd-42a8-af05-cfc02cafd818">

**Comment by deauthe** [comment]
I have tried expanding macros and I see that the InstantiateMsg struct/enum is not generated in my case

**Comment by jawoznia** [comment]
Hi @deauthe sorry for that. It seems we missed the update of versions in the `Cargo.toml`.

Please change the version in your contract to `1.0.0`:

```toml
sylvia = "1.0.2"
cosmwasm-schema = "2.0.2"
cosmwasm-std = "2.0.2"
schemars = "0.8.16"
serde = { version = "1.0.198", default-features = false, features = ["derive"] }
```
